# @package _global_

defaults:
  - ../env: null
  - ../method: act

demos: 40
num_pretrain_steps: 200000
num_pretrain_epochs: 10000
num_train_frames: 0
eval_every_steps: 2500
num_eval_episodes: 25
batch_size: 128
save_snapshot: true
snapshot_every_n: 1000
replay_size_before_train: 500

pixels: true
frame_stack: 4

is_imitation_learning: true

action_repeat: 1
action_sequence: 16
execution_length: 1
temporal_ensemble: true
use_standardization: false  # Demo-based standardization for action space
use_min_max_normalization: true  # Demo-based min-max normalization for action space
min_max_margin: 0
norm_obs: true

update_every_steps: 1

replay:
  nstep: 1
  num_workers: 0

method:
  lr: 3e-5
  lr_backbone: 3e-6
  actor_grad_clip: 1.0
  actor_model:
    kl_weight: 20

hydra:
  run:
    dir: ./exp_local/pixel_act/bigym_${env.task_name}_${now:%Y%m%d%H%M%S}
